baseURL = "https://clarustonus.lt/"
languageCode = "lt"
title = "Clarustonus"
theme = "hugo-simple"

disableKinds = ["RSS"]

[outputs]
home = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]

